kind: Deployment
apiVersion: apps/v1
metadata:
  name: edureka-project
  labels:
    app: abctechnologies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abctechnologies
  template:
    metadata:
      labels:
        app: abctechnologies
    spec:
       containers:
       - name: abctechnologiesjavaapp
         image: buntatiba/abctechnologies:build
         ports:
         - name: http
            containerPort: 8080