- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: Check if deployment exists
      shell: kubectl get deployment abctechnologies-1-0
      ignore_errors: true
      register: deployment_check

    - name: Deleting previous application deployment
      shell: kubectl delete deployment abctechnologies-1-0
      when: deployment_check.rc == 0

    - name: Creating new application deployment
      shell: kubectl create deployment abctechnologies-1-0 --image=buntatiba/abctechnologies:{{ build }} --port=8080
      when: deployment_check.rc != 0

    - name: Check if service exists
      shell: kubectl get service abctechnologies-1-0
      ignore_errors: true
      register: service_check

    - name: Creating new service
      shell: kubectl expose deployment abctechnologies-1-0 --type=NodePort --port=8080
      when: service_check.rc != 0
