- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: Deploying Application pods...
      shell: | 
         if [ `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep abctechnologies-1-0 | wc -l` -gt 0 ]; then  
            echo "Deleting previous application deployment"
            kubectl delete deployment `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep abctechnologies-1-0`
            echo "Creating new application deployment"
            kubectl create deployment abctechnologies-1-0 --image=buntatiba/abctechnologies:{{ build }} --port=8080
         else 
            echo "Deploying abctechnologies-1-0 Application"
            kubectl create deployment abctechnologies-1-0 --image=buntatiba/abctechnologies:{{ build }} --port=8080
         fi
    - name: deploying service
      shell: |
         if [ `kubectl get svc | grep abctechnologies-1-0  | awk '{print $1}' | wc -l` -gt 0 ]; then
            echo "App service found, No actions taken"
         else
            echo "Creating App Services"
            kubectl expose deployment abctechnologies-1-0 --name abctechnologies-1-0 --type NodePort --port 80 --target-port 8080
         fi
    - name: increase replicas 
      shell: kubectl scale deploy abctechnologies-1-0 --replicas=2
